// Package connstore adapts connect.json to the interfaces the hub and the
// data plane consume.
//
// It exists so internal/hub and internal/transport describe *what* they need
// ("the account with this token", "the bindings of this Bot") without importing
// the file format. The management API keeps talking to connect.Store directly,
// because it edits the document rather than consuming it.
package connstore

import (
	"encoding/json"
	"errors"
	"sort"
	"sync"
	"time"

	"github.com/LeiSureLyYrsc/OnebotNoa/internal/connect"
	"github.com/LeiSureLyYrsc/OnebotNoa/internal/hub"
	"github.com/LeiSureLyYrsc/OnebotNoa/internal/transport"
)

// Adapter wraps one connect.Store.
type Adapter struct {
	store *connect.Store

	// state keeps the live status and last-seen time per account. Those are
	// runtime facts, so they deliberately stay out of connect.json: rewriting the
	// connection file every few seconds would churn it and turn a reviewable
	// document into a log.
	mu       sync.RWMutex
	status   map[string]string
	lastSeen map[string]time.Time
	botSeen  map[int64]time.Time
}

// New builds the adapter.
func New(store *connect.Store) *Adapter {
	return &Adapter{
		store:    store,
		status:   map[string]string{},
		lastSeen: map[string]time.Time{},
		botSeen:  map[int64]time.Time{},
	}
}

// Store exposes the underlying document for the API layer.
func (a *Adapter) Store() *connect.Store { return a.store }

// ------------------------------------------------------------------ accounts

// AccountBySelfID implements hub.ConnStore.
func (a *Adapter) AccountBySelfID(selfID string) (hub.Account, bool) {
	account, ok := a.store.AccountBySelfID(selfID)
	if !ok {
		return hub.Account{}, false
	}
	return a.toHubAccount(account), true
}

// Accounts implements hub.ConnStore.
func (a *Adapter) Accounts() []hub.Account {
	rows := a.store.ListAccounts()
	out := make([]hub.Account, 0, len(rows))
	for _, account := range rows {
		out = append(out, a.toHubAccount(account))
	}
	return out
}

func (a *Adapter) toHubAccount(account connect.Account) hub.Account {
	a.mu.RLock()
	status := a.status[account.SelfID]
	a.mu.RUnlock()
	if status == "" {
		status = "offline"
	}
	return hub.Account{
		ID: account.ID, SelfID: account.SelfID, Name: account.Name,
		Nickname: account.Nickname, Avatar: account.Avatar, Enabled: account.Enabled,
		Tags: append([]string(nil), account.Tags...), Status: status,
	}
}

// AccountByToken resolves a pre-bound per-instance token.
func (a *Adapter) AccountByToken(token string) (hub.Account, bool) {
	account, ok := a.store.AccountByToken(token)
	if !ok {
		return hub.Account{}, false
	}
	return a.toHubAccount(account), true
}

// EnsureAccount creates the account behind an approved pending connection.
func (a *Adapter) EnsureAccount(selfID, source string) (hub.Account, bool, error) {
	account, created, err := a.store.EnsureAccount(selfID, "", source)
	if err != nil {
		return hub.Account{}, false, err
	}
	return a.toHubAccount(account), created, nil
}

// SetAccountToken binds a token generated by the API.
func (a *Adapter) SetAccountToken(id int64, plain, tokenHash, hint string) error {
	return a.store.SetAccountToken(id, plain, tokenHash, hint)
}

// AccountToken exposes a plaintext token (the WebUI shows it again when the
// operator asks; it is already stored sealed for the dial path).
func (a *Adapter) AccountToken(id int64) (string, error) {
	return a.store.AccountToken(id)
}

// PersistAccountState records the live state in memory, not on disk.
func (a *Adapter) PersistAccountState(selfID, status string) error {
	a.mu.Lock()
	a.status[selfID] = status
	a.lastSeen[selfID] = time.Now()
	a.mu.Unlock()
	return nil
}

// LastSeen reports when an account was last connected.
func (a *Adapter) LastSeen(selfID string) (time.Time, bool) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	at, ok := a.lastSeen[selfID]
	return at, ok
}

// LiveStatus reports the in-memory status of an account.
func (a *Adapter) LiveStatus(selfID string) string {
	a.mu.RLock()
	defer a.mu.RUnlock()
	if status := a.status[selfID]; status != "" {
		return status
	}
	return "offline"
}

// ---------------------------------------------------------------------- bots

// BotByID implements hub.ConnStore.
func (a *Adapter) BotByID(id int64) (hub.Bot, bool) {
	bot, ok := a.store.BotByID(id)
	if !ok {
		return hub.Bot{}, false
	}
	return toHubBot(bot), true
}

// BotByName implements hub.ConnStore.
func (a *Adapter) BotByName(name string) (hub.Bot, bool) {
	bot, ok := a.store.BotByName(name)
	if !ok {
		return hub.Bot{}, false
	}
	return toHubBot(bot), true
}

// Bots implements hub.ConnStore.
func (a *Adapter) Bots() []hub.Bot {
	rows := a.store.ListBots()
	out := make([]hub.Bot, 0, len(rows))
	for _, bot := range rows {
		out = append(out, toHubBot(bot))
	}
	return out
}

func toHubBot(bot connect.Bot) hub.Bot {
	return hub.Bot{
		ID: bot.ID, Name: bot.Name, Enabled: bot.Enabled, Note: bot.Note,
		RateLimit: bot.RateLimit, ActionPolicy: bot.ActionPolicy,
	}
}

// BotByToken resolves the token a Bot presents.
func (a *Adapter) BotByToken(token string) (hub.Bot, bool) {
	bot, ok := a.store.BotByToken(token)
	if !ok {
		return hub.Bot{}, false
	}
	return toHubBot(bot), true
}

// TouchBotSeen records the last time a Bot connected (in memory).
func (a *Adapter) TouchBotSeen(id int64) error {
	a.mu.Lock()
	a.botSeen[id] = time.Now()
	a.mu.Unlock()
	return nil
}

// BotLastSeen reports when a Bot was last seen.
func (a *Adapter) BotLastSeen(id int64) (time.Time, bool) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	at, ok := a.botSeen[id]
	return at, ok
}

// SetBotToken stores a freshly generated credential.
func (a *Adapter) SetBotToken(id int64, plain, tokenHash string) error {
	return a.store.SetBotToken(id, plain, tokenHash)
}

// ------------------------------------------------------------------ bindings

// Bindings implements hub.ConnStore.
func (a *Adapter) Bindings() []hub.JBinding {
	return a.toHubBindings(a.store.ListBindings())
}

// BindingsByBot implements hub.ConnStore.
func (a *Adapter) BindingsByBot(botName string) []hub.JBinding {
	return a.toHubBindings(a.store.BindingsByBot(botName))
}

// BindingsByAccount returns the grants of one account.
func (a *Adapter) BindingsByAccount(selfID string) []hub.JBinding {
	return a.toHubBindings(a.store.BindingsByAccount(selfID))
}

// BindingByPair returns one grant.
func (a *Adapter) BindingByPair(botName, selfID string) (hub.JBinding, bool) {
	binding, ok := a.store.BindingByPair(botName, selfID)
	if !ok {
		return hub.JBinding{}, false
	}
	return a.toHubBinding(binding), true
}

func (a *Adapter) toHubBindings(rows []connect.Binding) []hub.JBinding {
	out := make([]hub.JBinding, 0, len(rows))
	for _, binding := range rows {
		out = append(out, a.toHubBinding(binding))
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].AccountSelfID != out[j].AccountSelfID {
			return out[i].AccountSelfID < out[j].AccountSelfID
		}
		return out[i].Priority > out[j].Priority
	})
	return out
}

func (a *Adapter) toHubBinding(binding connect.Binding) hub.JBinding {
	var scope []byte
	if encoded, err := json.Marshal(binding.Scope); err == nil {
		scope = encoded
	}
	accountID := int64(0)
	if account, ok := a.store.AccountBySelfID(binding.AccountSelfID); ok {
		accountID = account.ID
	}
	botID := int64(0)
	if bot, ok := a.store.BotByName(binding.BotName); ok {
		botID = bot.ID
	}
	return hub.JBinding{
		ID: binding.ID, BotID: botID, BotName: binding.BotName,
		AccountID: accountID, AccountSelfID: binding.AccountSelfID,
		Priority: binding.Priority, IsDefault: binding.IsDefault, Enabled: binding.Enabled,
		Scope: scope,
	}
}

// ApplyBinding implements hub.ConnStore: it is how the hub-level "make this the
// default account" operation reaches the document.
func (a *Adapter) ApplyBinding(ref hub.BindingRef) error {
	binding, ok := a.store.BindingByPair(ref.BotName, ref.AccountSelfID)
	if !ok {
		return ErrNoBinding
	}
	return a.store.UpdateBinding(binding)
}

// ErrNoBinding reports a binding that disappeared between two calls.
var ErrNoBinding = errors.New("connstore: binding not found")

// ---------------------------------------------------------------- transport

// Plane adapts the document to the data plane's view.
//
// The data plane asks authorisation questions ("may this Bot use this
// account?"), while the hub deals in names and scopes. Projecting explicitly
// keeps each package's contract narrow instead of forcing one shape on both.
type Plane struct {
	store *connect.Store
}

// Plane returns the data-plane projection of the document.
func (a *Adapter) Plane() *Plane { return &Plane{store: a.store} }

// AccountBySelfID implements transport.ConnStore.
func (p *Plane) AccountBySelfID(selfID string) (transport.AccountRef, bool) {
	account, ok := p.store.AccountBySelfID(selfID)
	if !ok {
		return transport.AccountRef{}, false
	}
	return transport.AccountRef{ID: account.ID, SelfID: account.SelfID, Enabled: account.Enabled}, true
}

// AccountByToken implements transport.ConnStore.
func (p *Plane) AccountByToken(token string) (transport.AccountRef, bool) {
	account, ok := p.store.AccountByToken(token)
	if !ok {
		return transport.AccountRef{}, false
	}
	return transport.AccountRef{ID: account.ID, SelfID: account.SelfID, Enabled: account.Enabled}, true
}

// BotByToken implements transport.ConnStore.
func (p *Plane) BotByToken(token string) (transport.BotRef, bool) {
	bot, ok := p.store.BotByToken(token)
	if !ok {
		return transport.BotRef{}, false
	}
	return toPlaneBot(bot), true
}

// BotByID implements transport.ConnStore.
func (p *Plane) BotByID(id int64) (transport.BotRef, bool) {
	bot, ok := p.store.BotByID(id)
	if !ok {
		return transport.BotRef{}, false
	}
	return toPlaneBot(bot), true
}

// BotByName implements transport.ConnStore.
func (p *Plane) BotByName(name string) (transport.BotRef, bool) {
	bot, ok := p.store.BotByName(name)
	if !ok {
		return transport.BotRef{}, false
	}
	return toPlaneBot(bot), true
}

func toPlaneBot(bot connect.Bot) transport.BotRef {
	return transport.BotRef{
		ID: bot.ID, Name: bot.Name, Enabled: bot.Enabled,
		RateLimit: bot.RateLimit, ActionPolicy: bot.ActionPolicy,
	}
}

// BindingsByBot implements transport.ConnStore.
func (p *Plane) BindingsByBot(botName string) []transport.BindingRef {
	rows := p.store.BindingsByBot(botName)
	out := make([]transport.BindingRef, 0, len(rows))
	for _, binding := range rows {
		out = append(out, toPlaneBinding(binding))
	}
	return out
}

// BindingByPair implements transport.ConnStore.
func (p *Plane) BindingByPair(botName, selfID string) (transport.BindingRef, bool) {
	binding, ok := p.store.BindingByPair(botName, selfID)
	if !ok {
		return transport.BindingRef{}, false
	}
	return toPlaneBinding(binding), true
}

func toPlaneBinding(binding connect.Binding) transport.BindingRef {
	encoded, _ := json.Marshal(binding.Scope)
	return transport.BindingRef{
		BotName: binding.BotName, AccountSelfID: binding.AccountSelfID,
		Enabled: binding.Enabled, IsDefault: binding.IsDefault, Scope: encoded,
	}
}

// Connections implements transport.ConnStore.
func (p *Plane) Connections() []transport.ConnectionRef {
	rows := p.store.ListConnections()
	out := make([]transport.ConnectionRef, 0, len(rows))
	for _, connection := range rows {
		ref := transport.ConnectionRef{
			ID: connection.ID, Name: connection.Name, Kind: connection.Kind,
			Enabled: connection.Enabled, Addr: connection.Addr, URL: connection.URL,
			Path: connection.Path, Mode: connection.Mode,
			AccountSelfID: connection.AccountSelfID, BotName: connection.BotName,
			FixedSelfID: connection.FixedSelfID,
			TLSCert:     connection.TLSCert, TLSKey: connection.TLSKey,
			HasToken: connection.Grant.Token != "",
		}
		if connection.Reconnect != nil {
			ref.Min = connection.Reconnect.Min
			ref.Max = connection.Reconnect.Max
			ref.Jitter = connection.Reconnect.Jitter
		}
		out = append(out, ref)
	}
	return out
}

// ConnectionToken implements transport.ConnStore.
func (p *Plane) ConnectionToken(id int64) (string, error) {
	return p.store.ConnectionToken(id)
}

// ------------------------------------------------------------------ compile

var _ hub.ConnStore = (*Adapter)(nil)
var _ transport.ConnStore = (*Plane)(nil)
